// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-11-4.100.177
// firmware : 4.100.177 (user-4.100.177-cn-202609241530)
// sha256   : ff74c6f467529963b6afd40669437d8ec39a02e48c10d0893739847b3ba3dc2b
// revision : 1
// input_digest: 25b850e461c22925
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- recovered type layouts ----
// `#[repr(C, packed(N))]` + explicit padding reproduces the exact
// recovered byte layout and its target-declared alignment.
pub type canopus_interconnect_recv_cb = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *const u8) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct file_operations {
    pub open: *mut core::ffi::c_void, // +0x0
    pub close: *mut core::ffi::c_void, // +0x4
    pub read: *mut core::ffi::c_void, // +0x8
    pub write: *mut core::ffi::c_void, // +0xc
    pub lseek: *mut core::ffi::c_void, // +0x10
    pub ioctl: *mut core::ffi::c_void, // +0x14
    pub _tail: [u8; 0x18], // 24
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_order_record {
    pub app_name: [u8; 128], // +0x0
    pub _pad_80: [u8; 0x4], // 4
    pub flags: u32, // +0x84
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_lvx_event_cb = extern "C" fn(*mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct stock_timespec_t {
    pub tv_sec: i64, // +0x0
    pub tv_nsec: i32, // +0x8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_thirdparty_message_content {
    pub message_id: u32, // +0x0
    pub message_kind: u16, // +0x4
    pub _pad_6: [u8; 0xa], // 10
    pub package_name: *mut core::ffi::c_void, // +0x10
    pub fingerprint_blob: *mut core::ffi::c_void, // +0x14
    pub payload_blob: *mut core::ffi::c_void, // +0x18
    pub _tail: [u8; 0x134], // 308
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_page_descriptor {
    pub parent_descriptor: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0xc], // 12
    pub page_name: *mut core::ffi::c_void, // +0x10
    pub page_id: u16, // +0x14
    pub app_id: u16, // +0x16
    pub flags: u16, // +0x18
    pub _pad_1a: [u8; 0x2], // 2
    pub scheduler_deadline: i32, // +0x1c
    pub scheduler_priority: i32, // +0x20
    pub async_destroy_state: u32, // +0x24
    pub lifecycle_state: u8, // +0x28
    pub layer: u8, // +0x29
    pub page_kind: u8, // +0x2a
    pub _pad_2b: [u8; 0x1], // 1
    pub activity_context: *mut core::ffi::c_void, // +0x2c
    pub root_object: *mut core::ffi::c_void, // +0x30
    pub on_signal: *mut core::ffi::c_void, // +0x34
    pub runtime_default_56: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0x4], // 4
    pub registry_prev: *mut core::ffi::c_void, // +0x40
    pub registry_next: *mut core::ffi::c_void, // +0x44
    pub runtime_parent: *mut core::ffi::c_void, // +0x48
    pub on_create: *mut core::ffi::c_void, // +0x4c
    pub on_resume: *mut core::ffi::c_void, // +0x50
    pub on_foreground_data: *mut core::ffi::c_void, // +0x54
    pub extension_callback_88: *mut core::ffi::c_void, // +0x58
    pub on_pause: *mut core::ffi::c_void, // +0x5c
    pub on_stop: *mut core::ffi::c_void, // +0x60
    pub on_ui_destroy: *mut core::ffi::c_void, // +0x64
    pub extension_callback_104: *mut core::ffi::c_void, // +0x68
    pub extension_callback_108: *mut core::ffi::c_void, // +0x6c
    pub _tail: [u8; 0x8], // 8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_app_info {
    pub package_name: *mut core::ffi::c_void, // +0x0
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub icon_file: *mut core::ffi::c_void, // +0x8
    pub extra: *mut core::ffi::c_void, // +0xc
    pub fingerprint: [u8; 20], // +0x10
}

#[repr(C, packed(8))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_notification_message {
    pub message_id: u64, // +0x0
    pub repeat_count: u32, // +0x8
    pub title: *mut core::ffi::c_void, // +0xc
    pub source: *mut core::ffi::c_void, // +0x10
    pub body: *mut core::ffi::c_void, // +0x14
    pub auxiliary_text: *mut core::ffi::c_void, // +0x18
    pub small_icon_path: *mut core::ffi::c_void, // +0x1c
    pub large_icon_path: *mut core::ffi::c_void, // +0x20
    pub extension_text_36: *mut core::ffi::c_void, // +0x24
    pub extension_text_40: *mut core::ffi::c_void, // +0x28
    pub _pad_2c: [u8; 0x4], // 4
    pub timestamp: u64, // +0x30
    pub _pad_38: [u8; 0x4], // 4
    pub flags_60: [u8; 3], // +0x3c
    pub _pad_3f: [u8; 0x1], // 1
    pub action_callback: *mut core::ffi::c_void, // +0x40
    pub action_context: u32, // +0x44
    pub extension_72: u32, // +0x48
    pub extension_76: u32, // +0x4c
    pub open_callback: *mut core::ffi::c_void, // +0x50
    pub destroy_callback: *mut core::ffi::c_void, // +0x54
    pub start_reminder: u8, // +0x58
    pub flags_89: u8, // +0x59
    pub flags_90: u8, // +0x5a
    pub _pad_5b: [u8; 0x1], // 1
    pub callback_data: *mut core::ffi::c_void, // +0x5c
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct service_object {
    pub enabled_state: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub name: *mut core::ffi::c_void, // +0x4
    pub service_id: u8, // +0x8
    pub profile_group: u8, // +0x9
    pub _pad_a: [u8; 0x1a], // 26
    pub startup_cb: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x8], // 8
    pub startup_eligibility_cb: *mut core::ffi::c_void, // +0x30
    pub get_profile_cb: *mut core::ffi::c_void, // +0x34
    pub cleanup_cb: *mut core::ffi::c_void, // +0x38
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_interconnect_send_done = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_message {
    pub r#type: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub length: u32, // +0x4
    pub _pad_8: [u8; 0x8], // 8
    pub value: *mut core::ffi::c_void, // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct ordered_app_entry {
    pub app_name: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0x4], // 4
    pub enabled: u8, // +0x8
    pub hidden: u8, // +0x9
    pub _tail: [u8; 0x6], // 6
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_struct {
    pub name: [u8; 128], // +0x0
    pub flags: u8, // +0x80
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_record {
    pub app_id: u16, // +0x0
    pub _pad_2: [u8; 0x2], // 2
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub package_name: *mut core::ffi::c_void, // +0x8
    pub icon_name: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x8], // 8
    pub flags: u8, // +0x18
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_descriptor {
    pub registry_links: u64, // +0x0
    pub vtable: *mut core::ffi::c_void, // +0x8
    pub package_name: *mut core::ffi::c_void, // +0xc
    pub launcher_icon_resource: *mut core::ffi::c_void, // +0x10
    pub app_id: u16, // +0x14
    pub flags: u8, // +0x16
    pub _pad_17: [u8; 0x5], // 5
    pub owned_string_28: *mut core::ffi::c_void, // +0x1c
    pub owned_string_32: *mut core::ffi::c_void, // +0x20
    pub launcher_metadata_callback: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x10], // 16
    pub page_registry: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0xc], // 12
    pub hidden_flags: u8, // +0x48
    pub _tail: [u8; 0x7], // 7
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"4.100.177";
    const EXPECT_BUILD: &[u8] = b"user-4.100.177-cn-202609241530";
    if !identity_token_eq(0xca07fb6, EXPECT_VERSION) { return -1; }
    if !identity_token_eq(0xca0802e, EXPECT_BUILD) { return -1; }
    0
}

/// Compares an LF-, CR-, or NUL-terminated identity token.
fn identity_token_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0 || b == b'\n' || b == b'\r';
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `read` at 0xc33d74c. Thumb callable address 0xc33d74d.
pub const CANOPUS_FW_READ_CALLABLE: usize = canopus_thumb_callable(0xc33d74dusize);

/// Recovered global `font_reload_draw_unit_slot` at 0x200bd1bc.
pub const canopus_fw_font_reload_draw_unit_slot: usize = 0x200bd1bcusize;

/// Recovered `font_reload_gradient_pending_release` at 0xc395b38. Thumb callable address 0xc395b39.
pub const CANOPUS_FW_FONT_RELOAD_GRADIENT_PENDING_RELEASE_CALLABLE: usize = canopus_thumb_callable(0xc395b39usize);

/// Recovered `lvx_label_set_long_mode` at 0xc3b3ec0. Thumb callable address 0xc3b3ec1.
pub const CANOPUS_FW_LVX_LABEL_SET_LONG_MODE_CALLABLE: usize = canopus_thumb_callable(0xc3b3ec1usize);

/// Recovered `font_reload_cache_release` at 0xc8b7b6c. Thumb callable address 0xc8b7b6d.
pub const CANOPUS_FW_FONT_RELOAD_CACHE_RELEASE_CALLABLE: usize = canopus_thumb_callable(0xc8b7b6dusize);

/// Recovered `lv_obj_set_style_pad_bottom` at 0xc383798. Thumb callable address 0xc383799.
pub const CANOPUS_FW_LV_OBJ_SET_STYLE_PAD_BOTTOM_CALLABLE: usize = canopus_thumb_callable(0xc383799usize);

/// Recovered `cache_barrier` at 0xc91c922. Thumb callable address 0xc91c923.
pub const CANOPUS_FW_CACHE_BARRIER_CALLABLE: usize = canopus_thumb_callable(0xc91c923usize);

/// Recovered `lv_obj_align_to` at 0xc383f3c. Thumb callable address 0xc383f3d.
pub const CANOPUS_FW_LV_OBJ_ALIGN_TO_CALLABLE: usize = canopus_thumb_callable(0xc383f3dusize);

/// Recovered `lvx_page_title_create` at 0xc89cb3c. Thumb callable address 0xc89cb3d.
pub const CANOPUS_FW_LVX_PAGE_TITLE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc89cb3dusize);

/// Recovered `lvx_list_item_add_content` at 0xc50d240. Thumb callable address 0xc50d241.
pub const CANOPUS_FW_LVX_LIST_ITEM_ADD_CONTENT_CALLABLE: usize = canopus_thumb_callable(0xc50d241usize);

/// Recovered `lv_obj_clear_flag` at 0xc3822a6. Thumb callable address 0xc3822a7.
pub const CANOPUS_FW_LV_OBJ_CLEAR_FLAG_CALLABLE: usize = canopus_thumb_callable(0xc3822a7usize);

/// Recovered global `font_reload_count_cache_class` at 0x2ca14a00.
pub const canopus_fw_font_reload_count_cache_class: usize = 0x2ca14a00usize;

/// Recovered global `font_reload_vector_draw_unit_slot` at 0x200d216c.
pub const canopus_fw_font_reload_vector_draw_unit_slot: usize = 0x200d216cusize;

/// Recovered `gap_host_stock_receive` at 0xc862000. Thumb callable address 0xc862001.
pub const CANOPUS_FW_GAP_HOST_STOCK_RECEIVE_CALLABLE: usize = canopus_thumb_callable(0xc862001usize);

/// Recovered `lvx_object_set_size` at 0xc3836d2. Thumb callable address 0xc3836d3.
pub const CANOPUS_FW_LVX_OBJECT_SET_SIZE_CALLABLE: usize = canopus_thumb_callable(0xc3836d3usize);

/// Recovered `font_manager_generate_def_path` at 0xc490e4c. Thumb callable address 0xc490e4d.
pub const CANOPUS_FW_FONT_MANAGER_GENERATE_DEF_PATH_CALLABLE: usize = canopus_thumb_callable(0xc490e4dusize);

/// Recovered `lv_timer_del` at 0xc3abdd4. Thumb callable address 0xc3abdd5.
pub const CANOPUS_FW_LV_TIMER_DEL_CALLABLE: usize = canopus_thumb_callable(0xc3abdd5usize);

/// Recovered `font_reload_lv_free` at 0xc3abdbc. Thumb callable address 0xc3abdbd.
pub const CANOPUS_FW_FONT_RELOAD_LV_FREE_CALLABLE: usize = canopus_thumb_callable(0xc3abdbdusize);

/// Recovered global `style_misans_medium_24` at 0x200c0f00.
pub const canopus_fw_style_misans_medium_24: usize = 0x200c0f00usize;

/// Recovered `page_finish` at 0xc699974. Thumb callable address 0xc699975.
pub const CANOPUS_FW_PAGE_FINISH_CALLABLE: usize = canopus_thumb_callable(0xc699975usize);

/// Recovered global `umem_heap_descriptor` at 0x3c356b40.
pub const canopus_fw_umem_heap_descriptor: usize = 0x3c356b40usize;

/// Recovered `sdp_set_raw_attribute` at 0xc86d4a8. Thumb callable address 0xc86d4a9.
pub const CANOPUS_FW_SDP_SET_RAW_ATTRIBUTE_CALLABLE: usize = canopus_thumb_callable(0xc86d4a9usize);

/// Recovered `font_reload_outline_event` at 0xc398134. Thumb callable address 0xc398135.
pub const CANOPUS_FW_FONT_RELOAD_OUTLINE_EVENT_CALLABLE: usize = canopus_thumb_callable(0xc398135usize);

/// Recovered `lv_obj_remove_style_all` at 0xc383318. Thumb callable address 0xc383319.
pub const CANOPUS_FW_LV_OBJ_REMOVE_STYLE_ALL_CALLABLE: usize = canopus_thumb_callable(0xc383319usize);

/// Recovered `lvx_object_align` at 0xc38361c. Thumb callable address 0xc38361d.
pub const CANOPUS_FW_LVX_OBJECT_ALIGN_CALLABLE: usize = canopus_thumb_callable(0xc38361dusize);

/// Recovered `lvx_image_set_scale` at 0xc3ae3d2. Thumb callable address 0xc3ae3d3.
pub const CANOPUS_FW_LVX_IMAGE_SET_SCALE_CALLABLE: usize = canopus_thumb_callable(0xc3ae3d3usize);

/// Recovered `font_reload_count_cache_init` at 0xc3a9d70. Thumb callable address 0xc3a9d71.
pub const CANOPUS_FW_FONT_RELOAD_COUNT_CACHE_INIT_CALLABLE: usize = canopus_thumb_callable(0xc3a9d71usize);

/// Recovered `lv_bar_set_range` at 0xc3ad884. Thumb callable address 0xc3ad885.
pub const CANOPUS_FW_LV_BAR_SET_RANGE_CALLABLE: usize = canopus_thumb_callable(0xc3ad885usize);

/// Recovered `system_router_app_wrapper` at 0xc45ba42. Thumb callable address 0xc45ba43.
pub const CANOPUS_FW_SYSTEM_ROUTER_APP_WRAPPER_CALLABLE: usize = canopus_thumb_callable(0xc45ba43usize);

/// Recovered global `style_misans_medium_28` at 0x200c0f0c.
pub const canopus_fw_style_misans_medium_28: usize = 0x200c0f0cusize;

/// Recovered `write` at 0xc33dc16. Thumb callable address 0xc33dc17.
pub const CANOPUS_FW_WRITE_CALLABLE: usize = canopus_thumb_callable(0xc33dc17usize);

/// Recovered `font_reload_vector_compare` at 0xc69e288. Thumb callable address 0xc69e289.
pub const CANOPUS_FW_FONT_RELOAD_VECTOR_COMPARE_CALLABLE: usize = canopus_thumb_callable(0xc69e289usize);

/// Recovered global `font_reload_uikit_slot` at 0x200bd08c.
pub const canopus_fw_font_reload_uikit_slot: usize = 0x200bd08cusize;

/// Recovered `close` at 0xc33818c. Thumb callable address 0xc33818d.
pub const CANOPUS_FW_CLOSE_CALLABLE: usize = canopus_thumb_callable(0xc33818dusize);

/// Recovered `lvx_notification_insert_message` at 0xc8f11d4. Thumb callable address 0xc8f11d5.
pub const CANOPUS_FW_LVX_NOTIFICATION_INSERT_MESSAGE_CALLABLE: usize = canopus_thumb_callable(0xc8f11d5usize);

/// Recovered `lvx_label_create` at 0xc3ab228. Thumb callable address 0xc3ab229.
pub const CANOPUS_FW_LVX_LABEL_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ab229usize);

/// Recovered `bt_alloc` at 0xc3514ec. Thumb callable address 0xc3514ed.
pub const CANOPUS_FW_BT_ALLOC_CALLABLE: usize = canopus_thumb_callable(0xc3514edusize);

/// Recovered `app_launcher_add` at 0xc546c20. Thumb callable address 0xc546c21.
pub const CANOPUS_FW_APP_LAUNCHER_ADD_CALLABLE: usize = canopus_thumb_callable(0xc546c21usize);

/// Recovered global `font_reload_lv_initialized` at 0x200bd090.
pub const canopus_fw_font_reload_lv_initialized: usize = 0x200bd090usize;

/// Recovered `controller_crash_dump` at 0xc92a768. Thumb callable address 0xc92a769.
pub const CANOPUS_FW_CONTROLLER_CRASH_DUMP_CALLABLE: usize = canopus_thumb_callable(0xc92a769usize);

/// Recovered `bt_buffer_new` at 0xc86123a. Thumb callable address 0xc86123b.
pub const CANOPUS_FW_BT_BUFFER_NEW_CALLABLE: usize = canopus_thumb_callable(0xc86123busize);

/// Recovered `lv_obj_refresh_style` at 0xc382878. Thumb callable address 0xc382879.
pub const CANOPUS_FW_LV_OBJ_REFRESH_STYLE_CALLABLE: usize = canopus_thumb_callable(0xc382879usize);

/// Recovered `on_resume_wrapped` at 0xc694fe0. Thumb callable address 0xc694fe1.
pub const CANOPUS_FW_ON_RESUME_WRAPPED_CALLABLE: usize = canopus_thumb_callable(0xc694fe1usize);

/// Recovered global `umem_heap_slot` at 0x200b2330.
pub const canopus_fw_umem_heap_slot: usize = 0x200b2330usize;

/// Recovered global `kmem_heap_slot` at 0x200b0070.
pub const canopus_fw_kmem_heap_slot: usize = 0x200b0070usize;

/// Recovered `bt_l2cap_submit_cid` at 0xc86d434. Thumb callable address 0xc86d435.
pub const CANOPUS_FW_BT_L2CAP_SUBMIT_CID_CALLABLE: usize = canopus_thumb_callable(0xc86d435usize);

/// Recovered `font_reload_sw_dispatch` at 0xc394814. Thumb callable address 0xc394815.
pub const CANOPUS_FW_FONT_RELOAD_SW_DISPATCH_CALLABLE: usize = canopus_thumb_callable(0xc394815usize);

/// Recovered `lv_bar_set_value` at 0xc3ad818. Thumb callable address 0xc3ad819.
pub const CANOPUS_FW_LV_BAR_SET_VALUE_CALLABLE: usize = canopus_thumb_callable(0xc3ad819usize);

/// Recovered `font_reload_vector_drop` at 0xc69f6dc. Thumb callable address 0xc69f6dd.
pub const CANOPUS_FW_FONT_RELOAD_VECTOR_DROP_CALLABLE: usize = canopus_thumb_callable(0xc69f6ddusize);

/// Recovered `font_reload_list_remove` at 0xc3a4640. Thumb callable address 0xc3a4641.
pub const CANOPUS_FW_FONT_RELOAD_LIST_REMOVE_CALLABLE: usize = canopus_thumb_callable(0xc3a4641usize);

/// Recovered global `font_reload_vector_cache_slot` at 0x200d2170.
pub const canopus_fw_font_reload_vector_cache_slot: usize = 0x200d2170usize;

/// Recovered `register_driver` at 0xc913344. Thumb callable address 0xc913345.
pub const CANOPUS_FW_REGISTER_DRIVER_CALLABLE: usize = canopus_thumb_callable(0xc913345usize);

/// Recovered `font_reload_metrics_destroy` at 0xc326e0e. Thumb callable address 0xc326e0f.
pub const CANOPUS_FW_FONT_RELOAD_METRICS_DESTROY_CALLABLE: usize = canopus_thumb_callable(0xc326e0fusize);

/// Recovered `lv_image_set_src` at 0xc3b2b8c. Thumb callable address 0xc3b2b8d.
pub const CANOPUS_FW_LV_IMAGE_SET_SRC_CALLABLE: usize = canopus_thumb_callable(0xc3b2b8dusize);

/// Recovered `font_reload_metrics_create` at 0xc3a5e18. Thumb callable address 0xc3a5e19.
pub const CANOPUS_FW_FONT_RELOAD_METRICS_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3a5e19usize);

/// Recovered `unlink` at 0xc33dbb4. Thumb callable address 0xc33dbb5.
pub const CANOPUS_FW_UNLINK_CALLABLE: usize = canopus_thumb_callable(0xc33dbb5usize);

/// Recovered `bt_free` at 0xc34cc7c. Thumb callable address 0xc34cc7d.
pub const CANOPUS_FW_BT_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34cc7dusize);

/// Recovered `font_reload_face_compare` at 0xc3965ba. Thumb callable address 0xc3965bb.
pub const CANOPUS_FW_FONT_RELOAD_FACE_COMPARE_CALLABLE: usize = canopus_thumb_callable(0xc3965bbusize);

/// Recovered `sdp_unregister` at 0xc86d748. Thumb callable address 0xc86d749.
pub const CANOPUS_FW_SDP_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0xc86d749usize);

/// Recovered `sem_post` at 0xc359a90. Thumb callable address 0xc359a91.
pub const CANOPUS_FW_SEM_POST_CALLABLE: usize = canopus_thumb_callable(0xc359a91usize);

/// Recovered `bt_pair_request_reply` at 0xc46a930. Thumb callable address 0xc46a931.
pub const CANOPUS_FW_BT_PAIR_REQUEST_REPLY_CALLABLE: usize = canopus_thumb_callable(0xc46a931usize);

/// Recovered `lvx_style_apply` at 0xc502ed0. Thumb callable address 0xc502ed1.
pub const CANOPUS_FW_LVX_STYLE_APPLY_CALLABLE: usize = canopus_thumb_callable(0xc502ed1usize);

/// Recovered `font_reload_cache_acquire` at 0xc3a37c4. Thumb callable address 0xc3a37c5.
pub const CANOPUS_FW_FONT_RELOAD_CACHE_ACQUIRE_CALLABLE: usize = canopus_thumb_callable(0xc3a37c5usize);

/// Recovered `font_reload_ft_set_pixel_size` at 0xc8b6e40. Thumb callable address 0xc8b6e41.
pub const CANOPUS_FW_FONT_RELOAD_FT_SET_PIXEL_SIZE_CALLABLE: usize = canopus_thumb_callable(0xc8b6e41usize);

/// Recovered `sdp_commit` at 0xc86d634. Thumb callable address 0xc86d635.
pub const CANOPUS_FW_SDP_COMMIT_CALLABLE: usize = canopus_thumb_callable(0xc86d635usize);

/// Recovered `lv_timer_create` at 0xc3abc84. Thumb callable address 0xc3abc85.
pub const CANOPUS_FW_LV_TIMER_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3abc85usize);

/// Recovered `mm_mallinfo` at 0xc34ef94. Thumb callable address 0xc34ef95.
pub const CANOPUS_FW_MM_MALLINFO_CALLABLE: usize = canopus_thumb_callable(0xc34ef95usize);

/// Recovered `bt_queue_external` at 0xc861f2c. Thumb callable address 0xc861f2d.
pub const CANOPUS_FW_BT_QUEUE_EXTERNAL_CALLABLE: usize = canopus_thumb_callable(0xc861f2dusize);

/// Recovered `lv_obj_add_event_cb` at 0xc37fbec. Thumb callable address 0xc37fbed.
pub const CANOPUS_FW_LV_OBJ_ADD_EVENT_CB_CALLABLE: usize = canopus_thumb_callable(0xc37fbedusize);

/// Recovered `font_reload_outline_destroy` at 0xc3a0958. Thumb callable address 0xc3a0959.
pub const CANOPUS_FW_FONT_RELOAD_OUTLINE_DESTROY_CALLABLE: usize = canopus_thumb_callable(0xc3a0959usize);

/// Recovered `kmem_free` at 0xc34cc08. Thumb callable address 0xc34cc09.
pub const CANOPUS_FW_KMEM_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34cc09usize);

/// Recovered `bt_discovery_start` at 0xc46a3de. Thumb callable address 0xc46a3df.
pub const CANOPUS_FW_BT_DISCOVERY_START_CALLABLE: usize = canopus_thumb_callable(0xc46a3dfusize);

/// Recovered `rename` at 0xc33d764. Thumb callable address 0xc33d765.
pub const CANOPUS_FW_RENAME_CALLABLE: usize = canopus_thumb_callable(0xc33d765usize);

/// Recovered global `bt_l2cap_owner` at 0x200be740.
pub const canopus_fw_bt_l2cap_owner: usize = 0x200be740usize;

/// Recovered `bt_socket_client_sendrecv` at 0xc46a184. Thumb callable address 0xc46a185.
pub const CANOPUS_FW_BT_SOCKET_CLIENT_SENDRECV_CALLABLE: usize = canopus_thumb_callable(0xc46a185usize);

/// Recovered global `font_reload_display_list` at 0x200bd094.
pub const canopus_fw_font_reload_display_list: usize = 0x200bd094usize;

/// Recovered global `bt_shared_adapter` at 0x200c2ae0.
pub const canopus_fw_bt_shared_adapter: usize = 0x200c2ae0usize;

/// Recovered global `font_reload_style_refresh_enabled` at 0x200bd0b4.
pub const canopus_fw_font_reload_style_refresh_enabled: usize = 0x200bd0b4usize;

/// Recovered `mm_memalign` at 0xc3506d8. Thumb callable address 0xc3506d9.
pub const CANOPUS_FW_MM_MEMALIGN_CALLABLE: usize = canopus_thumb_callable(0xc3506d9usize);

/// Recovered `heap_free` at 0xc34cc7c. Thumb callable address 0xc34cc7d.
pub const CANOPUS_FW_HEAP_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34cc7dusize);

/// Recovered `bt_get_bond_state` at 0xc46a7f0. Thumb callable address 0xc46a7f1.
pub const CANOPUS_FW_BT_GET_BOND_STATE_CALLABLE: usize = canopus_thumb_callable(0xc46a7f1usize);

/// Recovered `bt_l2cap_disconnect` at 0xc86d40c. Thumb callable address 0xc86d40d.
pub const CANOPUS_FW_BT_L2CAP_DISCONNECT_CALLABLE: usize = canopus_thumb_callable(0xc86d40dusize);

/// Recovered `page_goto` at 0xc8ebac8. Thumb callable address 0xc8ebac9.
pub const CANOPUS_FW_PAGE_GOTO_CALLABLE: usize = canopus_thumb_callable(0xc8ebac9usize);

/// Recovered `font_manager_remove_path` at 0xc9030dc. Thumb callable address 0xc9030dd.
pub const CANOPUS_FW_FONT_MANAGER_REMOVE_PATH_CALLABLE: usize = canopus_thumb_callable(0xc9030ddusize);

/// Recovered `calendar_icon_generate` at 0xc547870. Thumb callable address 0xc547871.
pub const CANOPUS_FW_CALENDAR_ICON_GENERATE_CALLABLE: usize = canopus_thumb_callable(0xc547871usize);

/// Recovered `sem_wait` at 0xc359620. Thumb callable address 0xc359621.
pub const CANOPUS_FW_SEM_WAIT_CALLABLE: usize = canopus_thumb_callable(0xc359621usize);

/// Recovered `offload_property_apply` at 0xc4685e0. Thumb callable address 0xc4685e1.
pub const CANOPUS_FW_OFFLOAD_PROPERTY_APPLY_CALLABLE: usize = canopus_thumb_callable(0xc4685e1usize);

/// Recovered `font_reload_vector_destroy` at 0xc69f6ac. Thumb callable address 0xc69f6ad.
pub const CANOPUS_FW_FONT_RELOAD_VECTOR_DESTROY_CALLABLE: usize = canopus_thumb_callable(0xc69f6adusize);

/// Recovered `app_lookup_package` at 0xc69fa6a. Thumb callable address 0xc69fa6b.
pub const CANOPUS_FW_APP_LOOKUP_PACKAGE_CALLABLE: usize = canopus_thumb_callable(0xc69fa6busize);

/// Recovered `font_manager_add_path` at 0xc492450. Thumb callable address 0xc492451.
pub const CANOPUS_FW_FONT_MANAGER_ADD_PATH_CALLABLE: usize = canopus_thumb_callable(0xc492451usize);

/// Recovered `font_reload_glyph_metrics` at 0xc396ac0. Thumb callable address 0xc396ac1.
pub const CANOPUS_FW_FONT_RELOAD_GLYPH_METRICS_CALLABLE: usize = canopus_thumb_callable(0xc396ac1usize);

/// Recovered `bt_adapter_unregister` at 0xc46a364. Thumb callable address 0xc46a365.
pub const CANOPUS_FW_BT_ADAPTER_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0xc46a365usize);

/// Recovered `app_lookup` at 0xc6aa914. Thumb callable address 0xc6aa915.
pub const CANOPUS_FW_APP_LOOKUP_CALLABLE: usize = canopus_thumb_callable(0xc6aa915usize);

/// Recovered global `gap_host_receive_slot` at 0x200bd928.
pub const canopus_fw_gap_host_receive_slot: usize = 0x200bd928usize;

/// Recovered `font_reload_outline_release` at 0xc3a08f6. Thumb callable address 0xc3a08f7.
pub const CANOPUS_FW_FONT_RELOAD_OUTLINE_RELEASE_CALLABLE: usize = canopus_thumb_callable(0xc3a08f7usize);

/// Recovered `font_reload_glyph_pending_release` at 0xc399ac6. Thumb callable address 0xc399ac7.
pub const CANOPUS_FW_FONT_RELOAD_GLYPH_PENDING_RELEASE_CALLABLE: usize = canopus_thumb_callable(0xc399ac7usize);

/// Recovered `lv_obj_move_to_index` at 0xc383a78. Thumb callable address 0xc383a79.
pub const CANOPUS_FW_LV_OBJ_MOVE_TO_INDEX_CALLABLE: usize = canopus_thumb_callable(0xc383a79usize);

/// Recovered `lv_image_decoder_get_info` at 0xc38e44c. Thumb callable address 0xc38e44d.
pub const CANOPUS_FW_LV_IMAGE_DECODER_GET_INFO_CALLABLE: usize = canopus_thumb_callable(0xc38e44dusize);

/// Recovered `lv_display_get_horizontal_resolution` at 0xc381630. Thumb callable address 0xc381631.
pub const CANOPUS_FW_LV_DISPLAY_GET_HORIZONTAL_RESOLUTION_CALLABLE: usize = canopus_thumb_callable(0xc381631usize);

/// Recovered `app_install` at 0xc6a9718. Thumb callable address 0xc6a9719.
pub const CANOPUS_FW_APP_INSTALL_CALLABLE: usize = canopus_thumb_callable(0xc6a9719usize);

/// Recovered `bt_timer_cancel` at 0xc861378. Thumb callable address 0xc861379.
pub const CANOPUS_FW_BT_TIMER_CANCEL_CALLABLE: usize = canopus_thumb_callable(0xc861379usize);

/// Recovered `bt_timer_cancel_owned` at 0xc8613c0. Thumb callable address 0xc8613c1.
pub const CANOPUS_FW_BT_TIMER_CANCEL_OWNED_CALLABLE: usize = canopus_thumb_callable(0xc8613c1usize);

/// Recovered `calendar_icon_publish` at 0xc54779c. Thumb callable address 0xc54779d.
pub const CANOPUS_FW_CALENDAR_ICON_PUBLISH_CALLABLE: usize = canopus_thumb_callable(0xc54779dusize);

/// Recovered `lv_obj_get_style_prop` at 0xc380164. Thumb callable address 0xc380165.
pub const CANOPUS_FW_LV_OBJ_GET_STYLE_PROP_CALLABLE: usize = canopus_thumb_callable(0xc380165usize);

/// Recovered `lvgl_posix_open` at 0xc3a60bc. Thumb callable address 0xc3a60bd.
pub const CANOPUS_FW_LVGL_POSIX_OPEN_CALLABLE: usize = canopus_thumb_callable(0xc3a60bdusize);

/// Recovered `service_manager_startup` at 0xc90bc8c. Thumb callable address 0xc90bc8d.
pub const CANOPUS_FW_SERVICE_MANAGER_STARTUP_CALLABLE: usize = canopus_thumb_callable(0xc90bc8dusize);

/// Recovered `lvx_list_item_update` at 0xc50c3cc. Thumb callable address 0xc50c3cd.
pub const CANOPUS_FW_LVX_LIST_ITEM_UPDATE_CALLABLE: usize = canopus_thumb_callable(0xc50c3cdusize);

/// Recovered `lv_obj_tree_walk` at 0xc38151c. Thumb callable address 0xc38151d.
pub const CANOPUS_FW_LV_OBJ_TREE_WALK_CALLABLE: usize = canopus_thumb_callable(0xc38151dusize);

/// Recovered `font_reload_drop_face_id` at 0xc39a388. Thumb callable address 0xc39a389.
pub const CANOPUS_FW_FONT_RELOAD_DROP_FACE_ID_CALLABLE: usize = canopus_thumb_callable(0xc39a389usize);

/// Recovered `page_stack_get` at 0xc695818. Thumb callable address 0xc695819.
pub const CANOPUS_FW_PAGE_STACK_GET_CALLABLE: usize = canopus_thumb_callable(0xc695819usize);

/// Recovered global `font_reload_size_cache_class` at 0x2ca14980.
pub const canopus_fw_font_reload_size_cache_class: usize = 0x2ca14980usize;

/// Recovered `_lv_inv_area` at 0xc382080. Thumb callable address 0xc382081.
pub const CANOPUS_FW__LV_INV_AREA_CALLABLE: usize = canopus_thumb_callable(0xc382081usize);

/// Recovered `lvx_content_pad_bottom` at 0xc383798. Thumb callable address 0xc383799.
pub const CANOPUS_FW_LVX_CONTENT_PAD_BOTTOM_CALLABLE: usize = canopus_thumb_callable(0xc383799usize);

/// Recovered `font_reload_vg_dispatch` at 0xc391354. Thumb callable address 0xc391355.
pub const CANOPUS_FW_FONT_RELOAD_VG_DISPATCH_CALLABLE: usize = canopus_thumb_callable(0xc391355usize);

/// Recovered `lvx_object_create` at 0xc382ff0. Thumb callable address 0xc382ff1.
pub const CANOPUS_FW_LVX_OBJECT_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc382ff1usize);

/// Recovered global `mpu_region_bitmap` at 0x200f4080.
pub const canopus_fw_mpu_region_bitmap: usize = 0x200f4080usize;

/// Recovered `font_reload_metrics_compare` at 0xc39fcfe. Thumb callable address 0xc39fcff.
pub const CANOPUS_FW_FONT_RELOAD_METRICS_COMPARE_CALLABLE: usize = canopus_thumb_callable(0xc39fcffusize);

/// Recovered `heap_malloc` at 0xc3511b0. Thumb callable address 0xc3511b1.
pub const CANOPUS_FW_HEAP_MALLOC_CALLABLE: usize = canopus_thumb_callable(0xc3511b1usize);

/// Recovered `bt_discovery_stop` at 0xc46a406. Thumb callable address 0xc46a407.
pub const CANOPUS_FW_BT_DISCOVERY_STOP_CALLABLE: usize = canopus_thumb_callable(0xc46a407usize);

/// Recovered `ioctl` at 0xc341e00. Thumb callable address 0xc341e01.
pub const CANOPUS_FW_IOCTL_CALLABLE: usize = canopus_thumb_callable(0xc341e01usize);

/// Recovered `font_reload_face_destroy` at 0xc396a88. Thumb callable address 0xc396a89.
pub const CANOPUS_FW_FONT_RELOAD_FACE_DESTROY_CALLABLE: usize = canopus_thumb_callable(0xc396a89usize);

/// Recovered `open` at 0xc342c1c. Thumb callable address 0xc342c1d.
pub const CANOPUS_FW_OPEN_CALLABLE: usize = canopus_thumb_callable(0xc342c1dusize);

/// Recovered `errno_location` at 0xc349488. Thumb callable address 0xc349489.
pub const CANOPUS_FW_ERRNO_LOCATION_CALLABLE: usize = canopus_thumb_callable(0xc349489usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_errno_location() -> *const i32 {
    let f: extern "C" fn() -> *const i32 = unsafe { core::mem::transmute(CANOPUS_FW_ERRNO_LOCATION_CALLABLE) };
    f()
}

/// Recovered `bt_l2cap_connect` at 0xc86d388. Thumb callable address 0xc86d389.
pub const CANOPUS_FW_BT_L2CAP_CONNECT_CALLABLE: usize = canopus_thumb_callable(0xc86d389usize);

/// Recovered `cache_i_clean_invalidate_all` at 0xc0c181e. Thumb callable address 0xc0c181f.
pub const CANOPUS_FW_CACHE_I_CLEAN_INVALIDATE_ALL_CALLABLE: usize = canopus_thumb_callable(0xc0c181fusize);

/// Recovered `font_reload_image_pending_release` at 0xc395b48. Thumb callable address 0xc395b49.
pub const CANOPUS_FW_FONT_RELOAD_IMAGE_PENDING_RELEASE_CALLABLE: usize = canopus_thumb_callable(0xc395b49usize);

/// Recovered `bt_timer_add` at 0xc8c62f8. Thumb callable address 0xc8c62f9.
pub const CANOPUS_FW_BT_TIMER_ADD_CALLABLE: usize = canopus_thumb_callable(0xc8c62f9usize);

/// Recovered `lv_obj_set_width` at 0xc383658. Thumb callable address 0xc383659.
pub const CANOPUS_FW_LV_OBJ_SET_WIDTH_CALLABLE: usize = canopus_thumb_callable(0xc383659usize);

/// Recovered `font_reload_ft_mul_fix` at 0xc42426c. Thumb callable address 0xc42426d.
pub const CANOPUS_FW_FONT_RELOAD_FT_MUL_FIX_CALLABLE: usize = canopus_thumb_callable(0xc42426dusize);

/// Recovered `font_reload_cache_acquire_or_create` at 0xc3a7aa0. Thumb callable address 0xc3a7aa1.
pub const CANOPUS_FW_FONT_RELOAD_CACHE_ACQUIRE_OR_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3a7aa1usize);

/// Recovered `bt_adapter_register` at 0xc46a2fa. Thumb callable address 0xc46a2fb.
pub const CANOPUS_FW_BT_ADAPTER_REGISTER_CALLABLE: usize = canopus_thumb_callable(0xc46a2fbusize);

/// Recovered `bt_queue_free` at 0xc856d00. Thumb callable address 0xc856d01.
pub const CANOPUS_FW_BT_QUEUE_FREE_CALLABLE: usize = canopus_thumb_callable(0xc856d01usize);

/// Recovered `font_reload_outline_acquire` at 0xc3a7b6c. Thumb callable address 0xc3a7b6d.
pub const CANOPUS_FW_FONT_RELOAD_OUTLINE_ACQUIRE_CALLABLE: usize = canopus_thumb_callable(0xc3a7b6dusize);

/// Recovered `font_reload_lv_malloc` at 0xc3abd84. Thumb callable address 0xc3abd85.
pub const CANOPUS_FW_FONT_RELOAD_LV_MALLOC_CALLABLE: usize = canopus_thumb_callable(0xc3abd85usize);

/// Recovered `font_reload_face_create` at 0xc396718. Thumb callable address 0xc396719.
pub const CANOPUS_FW_FONT_RELOAD_FACE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc396719usize);

/// Recovered `font_reload_outline_compare` at 0xc39fd30. Thumb callable address 0xc39fd31.
pub const CANOPUS_FW_FONT_RELOAD_OUTLINE_COMPARE_CALLABLE: usize = canopus_thumb_callable(0xc39fd31usize);

/// Recovered `lv_cache_drop` at 0xc8b708a. Thumb callable address 0xc8b708b.
pub const CANOPUS_FW_LV_CACHE_DROP_CALLABLE: usize = canopus_thumb_callable(0xc8b708busize);

/// Recovered `lv_obj_set_local_style_prop` at 0xc383434. Thumb callable address 0xc383435.
pub const CANOPUS_FW_LV_OBJ_SET_LOCAL_STYLE_PROP_CALLABLE: usize = canopus_thumb_callable(0xc383435usize);

/// Recovered `bt_adapter_get_state` at 0xc46a3b8. Thumb callable address 0xc46a3b9.
pub const CANOPUS_FW_BT_ADAPTER_GET_STATE_CALLABLE: usize = canopus_thumb_callable(0xc46a3b9usize);

/// Recovered `lv_image_cache_drop` at 0xc3a37ec. Thumb callable address 0xc3a37ed.
pub const CANOPUS_FW_LV_IMAGE_CACHE_DROP_CALLABLE: usize = canopus_thumb_callable(0xc3a37edusize);

/// Recovered `bt_pair_display_reply` at 0xc46a96a. Thumb callable address 0xc46a96b.
pub const CANOPUS_FW_BT_PAIR_DISPLAY_REPLY_CALLABLE: usize = canopus_thumb_callable(0xc46a96busize);

/// Recovered global `font_reload_vector_label_class` at 0x2ca6cb78.
pub const canopus_fw_font_reload_vector_label_class: usize = 0x2ca6cb78usize;

/// Recovered `lseek` at 0xc33d4d8. Thumb callable address 0xc33d4d9.
pub const CANOPUS_FW_LSEEK_CALLABLE: usize = canopus_thumb_callable(0xc33d4d9usize);

/// Recovered `lv_image_create` at 0xc3ae134. Thumb callable address 0xc3ae135.
pub const CANOPUS_FW_LV_IMAGE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ae135usize);

/// Recovered `lv_bar_create` at 0xc3ad758. Thumb callable address 0xc3ad759.
pub const CANOPUS_FW_LV_BAR_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ad759usize);

/// Recovered `lvx_label_set_text` at 0xc3b38ac. Thumb callable address 0xc3b38ad.
pub const CANOPUS_FW_LVX_LABEL_SET_TEXT_CALLABLE: usize = canopus_thumb_callable(0xc3b38adusize);

/// Recovered global `font_reload_freetype_context_slot` at 0x200bd290.
pub const canopus_fw_font_reload_freetype_context_slot: usize = 0x200bd290usize;

/// Recovered `font_reload_outline_create` at 0xc3a8ae0. Thumb callable address 0xc3a8ae1.
pub const CANOPUS_FW_FONT_RELOAD_OUTLINE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3a8ae1usize);

/// Recovered `cache_d_clean_all` at 0xc92e5fa. Thumb callable address 0xc92e5fb.
pub const CANOPUS_FW_CACHE_D_CLEAN_ALL_CALLABLE: usize = canopus_thumb_callable(0xc92e5fbusize);

/// Recovered `hidden_and_show_app_cb` at 0xc546a54. Thumb callable address 0xc546a55.
pub const CANOPUS_FW_HIDDEN_AND_SHOW_APP_CB_CALLABLE: usize = canopus_thumb_callable(0xc546a55usize);

/// Recovered `clock_gettime` at 0xc34d4dc. Thumb callable address 0xc34d4dd.
pub const CANOPUS_FW_CLOCK_GETTIME_CALLABLE: usize = canopus_thumb_callable(0xc34d4ddusize);

/// Recovered `lv_obj_set_style_pad_top` at 0xc383782. Thumb callable address 0xc383783.
pub const CANOPUS_FW_LV_OBJ_SET_STYLE_PAD_TOP_CALLABLE: usize = canopus_thumb_callable(0xc383783usize);

/// Recovered `lvx_list_item_create` at 0xc50cc54. Thumb callable address 0xc50cc55.
pub const CANOPUS_FW_LVX_LIST_ITEM_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc50cc55usize);

/// Recovered `lvx_object_add_flag` at 0xc38221a. Thumb callable address 0xc38221b.
pub const CANOPUS_FW_LVX_OBJECT_ADD_FLAG_CALLABLE: usize = canopus_thumb_callable(0xc38221busize);

/// Recovered `protobuf_set_ordered_app_list` at 0xc549ee8. Thumb callable address 0xc549ee9.
pub const CANOPUS_FW_PROTOBUF_SET_ORDERED_APP_LIST_CALLABLE: usize = canopus_thumb_callable(0xc549ee9usize);

// ---- excluded symbols ----
// _lv_inv_area: restricted - not exported until context/ownership approved
// app_install: restricted - not exported until context/ownership approved
// app_launcher_add: restricted - not exported until context/ownership approved
// app_launcher_data_init: restricted - not exported until context/ownership approved
// app_launcher_del: restricted - not exported until context/ownership approved
// app_lookup: restricted - not exported until context/ownership approved
// app_lookup_package: restricted - not exported until context/ownership approved
// bt_adapter_get_instance: restricted - not exported until context/ownership approved
// bt_adapter_get_scan_mode: restricted - not exported until context/ownership approved
// bt_adapter_get_state: restricted - not exported until context/ownership approved
// bt_adapter_register: restricted - not exported until context/ownership approved
// bt_adapter_register_a2dp_callbacks: restricted - not exported until context/ownership approved
// bt_adapter_register_hfp_ag_callbacks: restricted - not exported until context/ownership approved
// bt_adapter_set_scan_mode: restricted - not exported until context/ownership approved
// bt_adapter_unregister: restricted - not exported until context/ownership approved
// bt_alloc: restricted - not exported until context/ownership approved
// bt_buffer_new: restricted - not exported until context/ownership approved
// bt_create_bond_private: restricted - not exported until context/ownership approved
// bt_discovery_start: restricted - not exported until context/ownership approved
// bt_discovery_stop: restricted - not exported until context/ownership approved
// bt_free: restricted - not exported until context/ownership approved
// bt_get_bond_state: restricted - not exported until context/ownership approved
// bt_get_pairing_state: restricted - not exported until context/ownership approved
// bt_l2cap_connect: restricted - not exported until context/ownership approved
// bt_l2cap_disconnect: restricted - not exported until context/ownership approved
// bt_l2cap_submit_cid: restricted - not exported until context/ownership approved
// bt_pair_display_reply: restricted - not exported until context/ownership approved
// bt_pair_request_reply: restricted - not exported until context/ownership approved
// bt_queue_external: restricted - not exported until context/ownership approved
// bt_queue_free: restricted - not exported until context/ownership approved
// bt_remove_bond_private: restricted - not exported until context/ownership approved
// bt_socket_client_sendrecv: restricted - not exported until context/ownership approved
// bt_socket_server_receive: restricted - not exported until context/ownership approved
// bt_timer_add: restricted - not exported until context/ownership approved
// bt_timer_cancel: restricted - not exported until context/ownership approved
// bt_timer_cancel_owned: restricted - not exported until context/ownership approved
// cache_barrier: restricted - not exported until context/ownership approved
// cache_d_clean_all: restricted - not exported until context/ownership approved
// cache_i_clean_invalidate_all: restricted - not exported until context/ownership approved
// calendar_icon_generate: restricted - not exported until context/ownership approved
// calendar_icon_publish: restricted - not exported until context/ownership approved
// clock_gettime: restricted - not exported until context/ownership approved
// close: restricted - not exported until context/ownership approved
// controller_crash_dump: restricted - not exported until context/ownership approved
// core_bt_pair_request_callback: restricted - not exported until context/ownership approved
// driver_close_dispatch: restricted - not exported until context/ownership approved
// driver_ioctl_dispatch: restricted - not exported until context/ownership approved
// firmware_log: restricted - not exported until context/ownership approved
// font_manager_add_path: restricted - not exported until context/ownership approved
// font_manager_generate_def_path: restricted - not exported until context/ownership approved
// font_manager_remove_path: restricted - not exported until context/ownership approved
// font_reload_cache_acquire: restricted - not exported until context/ownership approved
// font_reload_cache_acquire_or_create: restricted - not exported until context/ownership approved
// font_reload_cache_release: restricted - not exported until context/ownership approved
// font_reload_count_cache_init: restricted - not exported until context/ownership approved
// font_reload_drop_face_id: restricted - not exported until context/ownership approved
// font_reload_face_compare: restricted - not exported until context/ownership approved
// font_reload_face_create: restricted - not exported until context/ownership approved
// font_reload_face_destroy: restricted - not exported until context/ownership approved
// font_reload_ft_mul_fix: restricted - not exported until context/ownership approved
// font_reload_ft_set_pixel_size: restricted - not exported until context/ownership approved
// font_reload_glyph_metrics: restricted - not exported until context/ownership approved
// font_reload_glyph_pending_release: restricted - not exported until context/ownership approved
// font_reload_gradient_pending_release: restricted - not exported until context/ownership approved
// font_reload_image_pending_release: restricted - not exported until context/ownership approved
// font_reload_list_remove: restricted - not exported until context/ownership approved
// font_reload_lv_free: restricted - not exported until context/ownership approved
// font_reload_lv_malloc: restricted - not exported until context/ownership approved
// font_reload_metrics_compare: restricted - not exported until context/ownership approved
// font_reload_metrics_create: restricted - not exported until context/ownership approved
// font_reload_metrics_destroy: restricted - not exported until context/ownership approved
// font_reload_outline_acquire: restricted - not exported until context/ownership approved
// font_reload_outline_compare: restricted - not exported until context/ownership approved
// font_reload_outline_create: restricted - not exported until context/ownership approved
// font_reload_outline_destroy: restricted - not exported until context/ownership approved
// font_reload_outline_event: restricted - not exported until context/ownership approved
// font_reload_outline_release: restricted - not exported until context/ownership approved
// font_reload_sw_dispatch: restricted - not exported until context/ownership approved
// font_reload_vector_compare: restricted - not exported until context/ownership approved
// font_reload_vector_destroy: restricted - not exported until context/ownership approved
// font_reload_vector_drop: restricted - not exported until context/ownership approved
// font_reload_vg_dispatch: restricted - not exported until context/ownership approved
// gap_host_stock_receive: restricted - not exported until context/ownership approved
// heap_free: restricted - not exported until context/ownership approved
// heap_mallinfo: restricted - not exported until context/ownership approved
// heap_malloc: restricted - not exported until context/ownership approved
// heap_zalloc: restricted - not exported until context/ownership approved
// hfp_ag_connect: restricted - not exported until context/ownership approved
// hfp_ag_disconnect: restricted - not exported until context/ownership approved
// hidden_and_show_app_cb: restricted - not exported until context/ownership approved
// insmod: FORBIDDEN - no binding may ever be generated
// interconnect_close: restricted - not exported until context/ownership approved
// interconnect_connect: restricted - not exported until context/ownership approved
// interconnect_send: restricted - not exported until context/ownership approved
// ioctl: restricted - not exported until context/ownership approved
// kmem_free: restricted - not exported until context/ownership approved
// lseek: restricted - not exported until context/ownership approved
// lv_bar_create: restricted - not exported until context/ownership approved
// lv_bar_set_range: restricted - not exported until context/ownership approved
// lv_bar_set_value: restricted - not exported until context/ownership approved
// lv_cache_drop: restricted - not exported until context/ownership approved
// lv_display_get_horizontal_resolution: restricted - not exported until context/ownership approved
// lv_event_get_code: restricted - not exported until context/ownership approved
// lv_event_get_user_data: restricted - not exported until context/ownership approved
// lv_image_cache_drop: restricted - not exported until context/ownership approved
// lv_image_create: restricted - not exported until context/ownership approved
// lv_image_decoder_get_info: restricted - not exported until context/ownership approved
// lv_image_set_src: restricted - not exported until context/ownership approved
// lv_obj_add_event_cb: restricted - not exported until context/ownership approved
// lv_obj_align_to: restricted - not exported until context/ownership approved
// lv_obj_clear_flag: restricted - not exported until context/ownership approved
// lv_obj_get_style_prop: restricted - not exported until context/ownership approved
// lv_obj_move_to_index: restricted - not exported until context/ownership approved
// lv_obj_refresh_style: restricted - not exported until context/ownership approved
// lv_obj_remove_style_all: restricted - not exported until context/ownership approved
// lv_obj_set_hidden: restricted - not exported until context/ownership approved
// lv_obj_set_local_style_prop: restricted - not exported until context/ownership approved
// lv_obj_set_style_bg_opa: restricted - not exported until context/ownership approved
// lv_obj_set_style_pad_bottom: restricted - not exported until context/ownership approved
// lv_obj_set_style_pad_top: restricted - not exported until context/ownership approved
// lv_obj_set_width: restricted - not exported until context/ownership approved
// lv_obj_tree_walk: restricted - not exported until context/ownership approved
// lv_timer_create: restricted - not exported until context/ownership approved
// lv_timer_del: restricted - not exported until context/ownership approved
// lvgl_posix_open: restricted - not exported until context/ownership approved
// lvx_content_pad_bottom: restricted - not exported until context/ownership approved
// lvx_image_set_scale: restricted - not exported until context/ownership approved
// lvx_label_create: restricted - not exported until context/ownership approved
// lvx_label_set_long_mode: restricted - not exported until context/ownership approved
// lvx_label_set_text: restricted - not exported until context/ownership approved
// lvx_list_item_add_content: restricted - not exported until context/ownership approved
// lvx_list_item_create: restricted - not exported until context/ownership approved
// lvx_list_item_update: restricted - not exported until context/ownership approved
// lvx_list_row_create: restricted - not exported until context/ownership approved
// lvx_list_row_trailing: restricted - not exported until context/ownership approved
// lvx_msgbox_create: restricted - not exported until context/ownership approved
// lvx_msgbox_set_content: restricted - not exported until context/ownership approved
// lvx_notification_insert_message: restricted - not exported until context/ownership approved
// lvx_object_add_flag: restricted - not exported until context/ownership approved
// lvx_object_align: restricted - not exported until context/ownership approved
// lvx_object_create: restricted - not exported until context/ownership approved
// lvx_object_delete: restricted - not exported until context/ownership approved
// lvx_object_set_size: restricted - not exported until context/ownership approved
// lvx_page_content_create: restricted - not exported until context/ownership approved
// lvx_page_title_create: restricted - not exported until context/ownership approved
// lvx_style_apply: restricted - not exported until context/ownership approved
// mm_mallinfo: restricted - not exported until context/ownership approved
// mm_memalign: restricted - not exported until context/ownership approved
// modhandle: restricted - not exported until context/ownership approved
// offload_property_apply: restricted - not exported until context/ownership approved
// on_resume_wrapped: restricted - not exported until context/ownership approved
// open: restricted - not exported until context/ownership approved
// page_finish: restricted - not exported until context/ownership approved
// page_goto: restricted - not exported until context/ownership approved
// page_navigator_open_page: restricted - not exported until context/ownership approved
// page_stack_get: restricted - not exported until context/ownership approved
// protobuf_set_ordered_app_list: restricted - not exported until context/ownership approved
// pthread_create_internal: restricted - not exported until context/ownership approved
// quickapp_register_app: restricted - not exported until context/ownership approved
// read: restricted - not exported until context/ownership approved
// register_blockdriver: restricted - not exported until context/ownership approved
// register_driver: restricted - not exported until context/ownership approved
// rename: restricted - not exported until context/ownership approved
// rmmod: restricted - not exported until context/ownership approved
// sdp_builder_create: restricted - not exported until context/ownership approved
// sdp_commit: restricted - not exported until context/ownership approved
// sdp_set_raw_attribute: restricted - not exported until context/ownership approved
// sdp_unregister: restricted - not exported until context/ownership approved
// sem_post: restricted - not exported until context/ownership approved
// sem_trywait: restricted - not exported until context/ownership approved
// sem_wait: restricted - not exported until context/ownership approved
// service_manager_cleanup: restricted - not exported until context/ownership approved
// service_manager_get_profile: restricted - not exported until context/ownership approved
// service_manager_register: restricted - not exported until context/ownership approved
// service_manager_shutdown: restricted - not exported until context/ownership approved
// service_manager_startup: restricted - not exported until context/ownership approved
// sport_titlebar_dispatch: restricted - not exported until context/ownership approved
// system_router_app_wrapper: restricted - not exported until context/ownership approved
// system_router_get_pages_wrapper: restricted - not exported until context/ownership approved
// thirdparty_submit_message_content: restricted - not exported until context/ownership approved
// unlink: restricted - not exported until context/ownership approved
// unregister_blockdriver: restricted - not exported until context/ownership approved
// unregister_driver: restricted - not exported until context/ownership approved
// vendor_hci_transport_register: restricted - not exported until context/ownership approved
// watchface_manager_delete_watchface: restricted - not exported until context/ownership approved
// watchface_reset_watchface: restricted - not exported until context/ownership approved
// write: restricted - not exported until context/ownership approved

