// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-p65-3.100.043
// firmware : 3.100.043 (d516af0:nx_best1502p_ap)
// sha256   : a19b601477569765103eaf468b937bd8026b4d68ffa5c896bde222a79e475858
// revision : 1
// input_digest: 23b636d6026cd3a2
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"3.100.043";
    const EXPECT_BUILD: &[u8] = b"d516af0:nx_best1502p_ap";
    if !identity_token_eq(0x0C3BF9FD, EXPECT_VERSION) { return -1; }
    if !identity_token_eq(0x0CBFF458, EXPECT_BUILD) { return -1; }
    0
}

/// Compares an LF-, CR-, or NUL-terminated identity token.
fn identity_token_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0 || b == b'\n' || b == b'\r';
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
